- id: https://doi.org/10.1146/annurev-immunol-082423-035904 
  tags:
    - Immuno-mechanobiology
    
- id: https://doi.org/10.1101/2023.07.23.550231
  image: https://www.biorxiv.org/content/biorxiv/early/2023/07/25/2023.07.23.550231/F4.large.jpg?width=800&height=600&carousel=1
  extra-links: 
    - type: preprint
      link: https://doi.org/10.1101/2023.07.23.550231
  tags:
    - Immuno-mechanobiology

- id: https://doi.org/10.1101/2023.08.13.553152
  image: https://www.biorxiv.org/content/biorxiv/early/2023/08/15/2023.08.13.553152/F1.large.jpg?width=800&height=600&carousel=1
  extra-links: 
    - type: preprint
      link: https://doi.org/10.1101/2023.08.13.553152
  tags:
    - Immuno-mechanobiology

- id: https://doi.org/10.1038/s41467-022-34587-w
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41467-022-34587-w/MediaObjects/41467_2022_34587_Fig4_HTML.png?as=webp
  extra-links: 
    - type: source
      link: https://doi.org/10.1038/s41467-022-34587-w
  tags:
    - Immuno-mechanobiology
    
- id: https://doi.org/10.1038/s41467-023-38267-1
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41467-023-38267-1/MediaObjects/41467_2023_38267_Fig5_HTML.png?as=webp
  extra-links: 
    - type: source
      link: https://doi.org/10.1038/s41467-023-38267-1
  tags:
    - Immuno-mechanobiology

- id: https://doi.org/10.1063/5.0130805
  image: https://aipp.silverchair-cdn.com/aipp/content_public/journal/apb/7/1/10.1063_5.0130805/1/m_016102_1_f5.jpeg?Expires=1698830460&Signature=PEbOqOM4Oe3lKIuN20O7f6rfNt16B22ggESbbQaM5kf9dZ3gBvat6ekBr0JRETucqtaAh~W2JD6~ZZ81EmD3Q0f5BMbHZE0wL0q6jvLntD0jShD9hudSxLIs5KLXDX8PxjtNKKFD1C9UvQs8THmkjuoWlufv~mhfzzVXMR04Bv-qlSKtGgW2sEN1C6mVlxCBResRCXQNv~5pPLhrHfbLdX4d9eaxBW5RVc-Dcr3~z~sXFW8gjn6bBNL01Ty72XLQlrp1OwTBR-I-QzFqh~m0vFI3p4h1YNxZ5KQXI5MBibC4r1RD3CO6fbU12Qrztl28eEOge6vkKCBQoPLuv5YWlA__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  extra-links:
    - type: source
      link: https://doi.org/10.1063/5.0130805
  tags:
    - Immuno-mechanobiology

- id: https://doi.org/10.1080/09537104.2022.2071852
  image: https://www.tandfonline.com/na101/home/literatum/publisher/tandf/journals/content/iplt20/2022/iplt20.v033.i06/09537104.2022.2071852/20230216/images/large/iplt_a_2071852_f0001_b.jpeg
  extra-links:
    - type: source
      link: https://doi.org/10.1080/09537104.2022.2071852
  tags:
    - Platelet mechanobiology
 
- id: https://doi.org/10.1101/2023.01.09.523308
  image: https://www.biorxiv.org/content/biorxiv/early/2023/01/09/2023.01.09.523308/F2.large.jpg?width=800&height=600&carousel=1
  extra-links: 
    - type: preprint
      link: https://doi.org/10.7287/peerj.preprints.3100v1
  tags:
    - Platelet mechanobiology

- id: https://doi.org/10.1101/2022.01.17.476694
  image: https://www.biorxiv.org/content/biorxiv/early/2022/12/24/2022.01.17.476694/F2.large.jpg?width=800&height=600&carousel=1
  extra-links: 
    - type: preprint
      link: https://doi.org/10.1101/2022.01.17.476694
  tags:
    - Immuno-mechanobiology

- id: https://doi.org/10.1101/2022.04.14.488403
  image: https://www.biorxiv.org/content/biorxiv/early/2022/04/15/2022.04.14.488403/F1.large.jpg?width=800&height=600&carousel=1
  extra-links:
    - type: manubot
      link: https://doi.org/10.1101/2022.04.14.488403
  tags:
    - Immuno-mechanobiology
