- id: https://doi.org/10.1101/2023.08.13.553152
  image: https://www.biorxiv.org/content/biorxiv/early/2023/08/15/2023.08.13.553152/F1.large.jpg?width=800&height=600&carousel=1
  extra-links: 
    - type: preprint
      link: https://doi.org/10.1101/2023.08.13.553152
  tags:
    - Immuno-mechanobiology
    
- id: https://doi.org/10.1038/s41467-023-38267-1
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41467-023-38267-1/MediaObjects/41467_2023_38267_Fig5_HTML.png?as=webp
  extra-links: 
    - type: source
      link: https://doi.org/10.1038/s41467-023-38267-1
  tags:
    - Immuno-mechanobiology

- id: https://doi:10.1038/s41467-022-34587-w
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41467-022-34587-w/MediaObjects/41467_2022_34587_Fig4_HTML.png?as=webp
  extra-links:
    - type: source
      link: https://doi.org/10.1038/s41467-022-34587-w
  tags:
    - Immuno-mechanobiology

- id: https://doi.org/10.1063/5.0130805
  image: https://aip.scitation.org/na101/home/literatum/publisher/aip/journals/content/apb/2023/apb.2023.7.issue-1/5.0130805/20230106/images/small/5.0130805.figures.online.f2.gif
  extra-links:
    - type: source
      link: https://doi.org/10.1063/5.0130805
  tags:
    - Immuno-mechanobiology

- id: https://doi.org/10.1080/09537104.2022.2071852
  image: https://www.tandfonline.com/na101/home/literatum/publisher/tandf/journals/content/iplt20/2022/iplt20.v033.i06/09537104.2022.2071852/20230216/images/large/iplt_a_2071852_f0001_b.jpeg
  extra-links:
    - type: source
      link: https://doi.org/10.1080/09537104.2022.2071852
  tags:
    - Platelet mechanobiology
 
- id: https://doi.org/10.1101/2023.01.09.523308
  image: https://www.biorxiv.org/content/biorxiv/early/2023/01/09/2023.01.09.523308/F2.large.jpg?width=800&height=600&carousel=1
  extra-links: 
    - type: preprint
      link: https://doi.org/10.7287/peerj.preprints.3100v1
  tags:
    - Platelet mechanobiology

- id: https://doi.org/10.1101/2022.01.17.476694
  image: https://www.biorxiv.org/content/biorxiv/early/2022/12/24/2022.01.17.476694/F2.large.jpg?width=800&height=600&carousel=1
  extra-links: 
    - type: preprint
      link: https://doi.org/10.1101/2022.01.17.476694
  tags:
    - Immuno-mechanobiology

- id: https://doi.org/10.1101/2022.04.14.488403
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg
  extra-links:
    - type: manubot
      link: https://doi.org/10.1101/2022.04.14.488403
  tags:
    - Immuno-mechanobiology
