- id: doi:10.1038/s41467-022-34587-w
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41467-022-34587-w/MediaObjects/41467_2022_34587_Fig4_HTML.png?as=webp
  extra-links:
    - type: source
      link: https://doi.org/10.1038/s41467-022-34587-w
  tags:
    - Immuno-mechanobiology

- id: https://doi.org/10.1063/5.0130805
  image: https://aip.scitation.org/na101/home/literatum/publisher/aip/journals/content/apb/2023/apb.2023.7.issue-1/5.0130805/20230106/images/small/5.0130805.figures.online.f2.gif
  extra-links:
    - type: source
      link: https://doi.org/10.1063/5.0130805
  tags:
    - Immuno-mechanobiology

- id: https://doi.org/10.1080/09537104.2022.2071852
  image: https://www.tandfonline.com/na101/home/literatum/publisher/tandf/journals/content/iplt20/2022/iplt20.v033.i06/09537104.2022.2071852/20230216/images/large/iplt_a_2071852_f0001_b.jpeg
  extra-links:
    - type: source
      link: https://doi.org/10.1080/09537104.2022.2071852
  tags:
    - Platelet mechanobiology
 
- id: https://doi.org/10.1101/2023.01.09.523308
  image: https://www.biorxiv.org/content/biorxiv/early/2023/01/09/2023.01.09.523308/F2.large.jpg?width=800&height=600&carousel=1
  extra-links: 
    - type: preprint
      link: https://doi.org/10.7287/peerj.preprints.3100v1
  tags:
    - Platelet mechanobiology

- id: https://doi.org/10.1101/2022.01.17.476694
  image: https://www.biorxiv.org/content/biorxiv/early/2022/12/24/2022.01.17.476694/F2.large.jpg?width=800&height=600&carousel=1
  extra-links: 
    - type: preprint
      link: https://doi.org/10.1101/2022.01.17.476694
  tags:
    - Immuno-mechanobiology

# -id: https://doi.org/10.1242/jcs.258046
#   image: https://cob.silverchair-cdn.com/cob/content_public/journal/jcs/134/18/10.1242_jcs.258046/1/jcs25804603.png?Expires=1683816330&Signature=OuS7FU-m6pEKJeVSJfbSpQ8AzF~ZKdtUHxQCpDOzO1MSYfQQ531jKi-kJL1THGj66dvI2UeO~QOOuAu3HOOTOzubVPddDZk9oorzKo-XrH7DM0Gu3KSf2uvaSad1JM48Rv0iYLTFJJG0I~~TLbmc3P8Ag7Ak773qAUtA~GX7JH4eijU2DaKy4ZQrjWy~n6l2Bj3hpx8CGqSNEdkwMu16YShdRla3CuixwKoH4AHDZpZcWPO6zRXGVuZN6iIgH2ftGc0vzAx5jUztnX-HWfj-qoL5IsyKCxNtK160rT5iMhhQx2GzkduG4L2NIfeSy1VXshy56ne13kSOxQE-nraFdg__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
#   extra-links:
#     - type: source
#       link: https://doi.org/10.1242/jcs.258046
#   tags:
#     - Immuno-mechanobiology
  
# -id: https://doi.org/10.1101/2022.04.14.488403
#   image: https://www.biorxiv.org/content/biorxiv/early/2022/04/15/2022.04.14.488403/F1.large.jpg?width=800&height=600&carousel=1
#   extra-links:
#     - type: preprint
#       link: https://doi.org/10.1101/2022.04.14.488403
#   tags:
#     - Immuno-mechanobiology

# -id: https://doi.org/10.1038/s41590-019-0491-1
#   image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41590-019-0491-1/MediaObjects/41590_2019_491_Fig2_HTML.png?as=webp
#   extra-links:
#     - type: source
#       link: https://doi.org/10.1038/s41590-019-0491-1
#   tags:
#     - Immuno-mechanobiology

# - id: https://doi.org/10.1038/s41563-019-0323-6
#   image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41563-019-0323-6/MediaObjects/41563_2019_323_Fig1_HTML.png?as=webp
#   extra-links: 
#     - type: source
#       link: https://doi.org/10.1038/s41563-019-0323-6
#   tags:
#     - Platelet mechanobiology

# -id: https://doi.org/10.1016/j.molcel.2018.12.018
#   image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41590-019-0491-1/MediaObjects/41590_2019_491_Fig2_HTML.png?as=webp
#   extra-links:
#     - type: source
#       link: https://ars.els-cdn.com/content/image/1-s2.0-S1097276518310724-gr6.jpg
#   tags:
#     - Immuno-mechanobiology

# -id: https://doi.org/10.1038/s41590-018-0259-z
#   image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41590-018-0259-z/MediaObjects/41590_2018_259_Fig7_HTML.png?as=webp
#   extra-links:
#     - type: source
#       link: https://doi.org/10.1038/s41590-018-0259-z
#   tags:
#     - Immuno-mechanobiology

# - id: https://doi.org/10.1039/C8LC00464A
#   extra-links: 
#     - type: source
#       link: https://doi.org/10.1039/C8LC00464A
#   tags:
#     - Platelet mechanobiology

# -id: https://doi.org/10.1074/jbc.M116.763888
#   image: https://www.jbc.org/cms/attachment/ab393306-716e-4624-ba1d-43f3764c4c1b/gr1.jpg
#   extra-links:
#     - type: source
#       link: https://doi.org/10.1074/jbc.M116.763888
#   tags:
#     - Immuno-mechanobiology



- id: doi:10.1016/j.csbj.2020.05.017
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg
  date: 2020-6-2
  extra-links:
    - type: manubot
      link: https://greenelab.github.io/knowledge-graph-review/
  tags:
    - knowledge graphs

- id: doi:10.1371/journal.pcbi.1007128
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  repo: greenelab/meta-review
  extra-links:
    - type: manubot
      link: https://greenelab.github.io/meta-review/
    - type: source
      link: https://github.com/greenelab/meta-review
    - type: website
      link: http://manubot.org/

- id: doi:10.7554/eLife.32822
  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
  extra-links:
    - type: preprint
      link: https://doi.org/10.7287/peerj.preprints.3100v1
    - type: manubot
      link: https://greenelab.github.io/scihub-manuscript/
    - type: source
      link: https://github.com/greenelab/scihub-manuscript
      text: Manuscript source
    - type: source
      link: https://github.com/greenelab/scihub
      text: Analyses source
